Repository jornadayu/conversational-form, pull requests merged in 2023-05, with the labels that each got.

#2 Add missing build step to new releases action
  .github/workflows/new_release.yml
Labels: enhancement, ignore-jira-link

#3 Fix broken permissions with GitHub releases
  .github/workflows/new_release.yml
Labels: ci/cd, ignore-jira-link

#4 Complementa o codigo de exemplo no readme.md
  README.md
  examples/src/Chatbot.tsx
Labels: enhancement, ignore-jira-link

#6 Add action that links jira tasks
  .github/workflows/link-jira.yml
  .github/workflows/link_jira.yml
Labels: ci/cd, ignore-jira-link

#5 Exportando função e tipagem do useJobAutosave
  .github/workflows/linting.yml
  src/index.tsx
Labels: enhancement, ignore-jira-link

#7 [YURI-33] - Verificação de chatbot já respondido
  README.md
  examples/src/Chatbot.tsx
  src/components/chatbot/chatbot.ts
  src/scripts/cf/ConversationalForm.ts
  src/scripts/cf/logic/FlowManager.ts
Labels: enhancement

#8 Adding tests
  .github/workflows/linting.yml
  package.json
  tests/ExampleTest.test.ts
  tests/chatbot.test.ts
  vitest.config.ts
  yarn.lock
Labels: enhancement, ignore-jira-link
